# Generated by Django 5.0.1 on 2024-01-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_agua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('fat_id', models.AutoField(primary_key=True, serialize=False)),
                ('leituraatual', models.IntegerField()),
                ('consumofaturado', models.IntegerField()),
                ('fat_divida', models.IntegerField()),
                ('fat_mes', models.CharField(max_length=20)),
                ('fat_ano', models.CharField(max_length=4)),
                ('fat_key', models.IntegerField()),
                ('valordafatura', models.IntegerField()),
                ('fat_emissao', models.DateTimeField()),
                ('fat_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_agua.cliente')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('pag_id', models.AutoField(primary_key=True, serialize=False)),
                ('valordafatura', models.FloatField()),
                ('pag_totalpago', models.FloatField()),
                ('pag_divida', models.FloatField()),
                ('pag_mes', models.CharField(max_length=10)),
                ('pag_ano', models.CharField(max_length=10)),
                ('pag_key', models.IntegerField()),
                ('pag_idgroup', models.TextField()),
                ('pag_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_agua.cliente')),
            ],
        ),
    ]
