# Generated by Django 5.0.1 on 2024-01-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0003_alter_pagamento_pag_totalpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pag_idgroup',
            field=models.TextField(null=True),
        ),
    ]
