# Generated by Django 5.0.1 on 2024-01-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0007_alter_fatura_fat_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='fat_vencimento',
        ),
    ]
