# Generated by Django 5.0.1 on 2024-01-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cliente', models.IntegerField(unique=True)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('telefone_cliente', models.CharField(max_length=40)),
                ('endereco_cliente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Definicao',
            fields=[
                ('def_id', models.AutoField(primary_key=True, serialize=False)),
                ('def_consumomin', models.IntegerField()),
                ('def_metrocubico', models.FloatField()),
                ('def_taxafixa', models.FloatField()),
                ('def_iva', models.IntegerField()),
                ('def_vencimentoday', models.CharField(max_length=40)),
                ('def_multaforadoprazo', models.FloatField()),
                ('multar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='null', max_length=255)),
                ('user_username', models.CharField(default='null', max_length=40)),
                ('user_pass', models.CharField(default='null', max_length=10)),
                ('user_nivel', models.CharField(default='null', max_length=10)),
                ('user_key', models.IntegerField(default='1')),
                ('user_status', models.CharField(default='null', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=20)),
                ('valor', models.FloatField()),
                ('dia', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=10)),
                ('vda', models.CharField(max_length=40)),
                ('doc_id', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_agua.usuario')),
            ],
        ),
    ]
