# Generated by Django 5.0.1 on 2024-01-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='valor',
            field=models.CharField(max_length=30),
        ),
    ]
