# Generated by Django 5.0.1 on 2024-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agua', '0002_alter_atividade_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='doc_id',
            field=models.IntegerField(null=True),
        ),
    ]
