# Generated by Django 5.0.1 on 2024-01-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agua', '0004_alter_atividade_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
